export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";



export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";


export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const ADD_PROJECT_REQUEST = "ADD_PROJECT_REQUEST";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAIL = "ADD_PROJECT_SUCCESS";

export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAIL = "GET_PROJECT_FAIL";

export const GET_All_PROJECT_REQUEST = "GET_All_PROJECT_REQUEST";
export const GET_All_PROJECT_SUCCESS = "GET_All_PROJECT_SUCCESS";
export const GET_All_PROJECT_FAIL = "GET_All_PROJECT_FAIL";

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";
export const DELETE_PROJECT_RESET = "DELETE_PROJECT_RESET";

export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";
export const UPDATE_PROJECT_RESET = "UPDATE_PROJECT_RESET";

export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL"

export const GET_ERR_LOGS_PROJECT_REQUEST = "GET_ERR_LOGS_PROJECT_REQUEST";
export const GET_ERR_LOGS_PROJECT_SUCCESS = "GET_ERR_LOGS_PROJECT_SUCCESS";
export const GET_ERR_LOGS_PROJECT_FAIL = "GET_ERR_LOGS_PROJECT_FAIL";

export const PROJECT_SECRET_KEY_REQUEST = "PROJECT_SECRET_KEY_REQUEST";
export const PROJECT_SECRET_KEY_SUCCESS = "PROJECT_SECRET_KEY_SUCCESS";
export const PROJECT_SECRET_KEY_FAIL = "PROJECT_SECRET_KEY_FAIL";

export const PROJECT_TEXTTAG_REQUEST="PROJECT_TEXTTAG_REQUEST";
export const PROJECT_TEXTTAG_SUCCESS="PROJECT_TEXTTAG_SUCCESS"
export const PROJECT_TEXTTAG_FAIL="PROJECT_TEXTTAG_FAIL"

export const CLEAR_ERROR = "CLEAR_ERRORS";
